version: '3.8'

networks:
  sample_app_network:
    driver: bridge

services:
  spark-master:
    container_name: spark-master
    # This build the Dockerfile which present in the .(dot) directory . Which is current directory.
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    networks:
      - sample_app_network
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-worker1:
    container_name: spark-worker1
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    networks:
      - sample_app_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

  spark-worker2:
    container_name: spark-worker2
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    networks:
      - sample_app_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
